- label: Architecture Decision Records
  links:
    - label: Use Markdown Architectural Decision Records
      href: /blueprints/blueprint/docs/adr/0000-use-markdown-architectural-decision-records
    - label: Use GNU GPL as license
      href: /blueprints/blueprint/docs/adr/0001-use-gpl3-as-license
    - label: Operate First deployment feature selection Policy
      href: /blueprints/blueprint/docs/adr/0003-feature-selection-policy
- label: Continuous Delivery
  links:
    - label: (Opinionated) Continuous Delivery
      href: /blueprints/continuous-delivery/docs/continuous_delivery
    - label: Setting up Source Code Operations
      href: /blueprints/continuous-delivery/docs/setup_source_operations
    - label: Setting up a Continuous Integration Pipeline
      href: /blueprints/continuous-delivery/docs/setup_ci_pipeline
    - label: Setting up a Continuous Delivery Pipeline
      href: /blueprints/continuous-delivery/docs/setup_cd_pipeline