- label: ArgoCD Operations
  links:
    - label: Create ArgoCD Application Manifest
      href: /operators/continuous-deployment/docs/create_argocd_application_manifest
    - label: Get ArgoCD to Manage your app
      href: /operators/continuous-deployment/docs/get_argocd_to_manage_your_app
    - label: Give ArgoCD Access to your Project
      href: /operators/continuous-deployment/docs/give_argocd_access_to_your_project
    - label: Inclusions Explained
      href: /operators/continuous-deployment/docs/inclusions_explained
    - label: ArgoCD Setup
      href: /operators/continuous-deployment/docs/setup_argocd_dev_environment
- label: CRC
  links:
    - label: CRC Setup
      href: /operators/continuous-deployment/docs/downstream/crc
    - label: Installing ODH on CRC
      href: /operators/continuous-deployment/docs/downstream/odh-install-crc
    - label: CRC Disk Size
      href: /operators/continuous-deployment/docs/downstream/crc-disk-size
- label: Quicklab
  links:
    - label: Quicklab Setup
      href: /operators/continuous-deployment/docs/downstream/quicklab
    - label: Create persistent volumes
      href: /operators/continuous-deployment/docs/downstream/on-cluster-persistent-storage/README
    - label: Installing ODH on Quicklab
      href: /operators/continuous-deployment/docs/downstream/odh-install-quicklab
- label: MOC - ODH Operations
  links:
    - label: Getting Access
      href: /operators/moc-cnv-sandbox/docs/about-the-cluster
