apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operate-first
commonLabels:
  app: operate-first-app
  app.kubernetes.io/part-of: operate-first-app
resources:
- deployment.yaml
- routes.yaml
- service.yaml
