kind: Service
apiVersion: v1
metadata:
  name: operate-first-app
spec:
  selector:
    deployment: operate-first-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 8080
